spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:18080/realms/ssb-realm
  datasource:
    url: jdbc:postgresql://localhost:5433/ppdtcore
    username: postgres
    password: 00889977
  data:
    mongodb:
      uri: mongodb+srv://a4anaskhan3:00889977%40a@cluster0.u3vfif2.mongodb.net/ppdtcore
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  frontend-url: http://localhost:5173/
  auth-url: http://localhost:18080

  config:
    activate:
      on-profile: dev

cloudinary:
  cloud-name: dh0yikasy
  api-key: 419343789612165
  api-secret: T1WQcAxQHCWaLrVrGW6vl0GQQxA

keycloak:
  base-url: http://localhost:18080
  realm: ssb-realm
  client-id: ssb-backend
  client-secret: ${KEYCLOAK_CLIENT_SECRET}

server:
  port: 9000

fastapi:
  news:
    url: http://localhost:8000/news
  analyse:
    url: http://localhost:8001/analyze/ppdt
