spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SUPABASE_URL}/auth/v1
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}

  data:
    mongodb:
      uri: ${MONGO_URI}

  jpa:
    hibernate:
      ddl-auto: validate  # Allow schema updates in production (careful with deletions)
    show-sql: false

app:
  frontend-url: ${FRONTEND_URL}
  auth-url: ${SUPABASE_URL}
  api-key: ${SSB_API_KEY}


  config:
    activate:
      on-profile: prod

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}


fastapi:
  srt: ${FASTAPI_SRT_URL}
  wat: ${FASTAPI_WAT_URL}
  tat: ${FASTAPI_TAT_URL}
  news:
    url: ${NEWS_SERVICE_URL}
ai:
  lecturette:
    url: ${AI_LECTURETTE_URL}
