spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SUPABASE_URL}
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}

  data:
    mongodb:
      uri: ${MONGO_URI}

  jpa:
    hibernate:
      ddl-auto: validate # never update schema in prod automatically
    show-sql: false

app:
  frontend-url: ${FRONTEND_URL}
  auth-url: ${SUPABASE_URL}


  config:
    activate:
      on-profile: prod

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}


fastapi:
  news:
    url: ${NEWS_SERVICE_URL}
  analyse:
    url: ${ANALYSE_SERVICE_URL}
