spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:18080/realms/ssb-realm}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/ppdtcore}
    username: ${DB_USER:postgres}
    password: ${POSTGRES_PASSWORD}
  data:
    mongodb:
      uri: ${MONGO_URI}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  frontend-url: ${FRONTEND_URL:http://localhost:5173/}
  auth-url: ${AUTH_URL:http://localhost:18080}

  config:
    activate:
      on-profile: dev

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

keycloak:
  base-url: ${KEYCLOAK_BASE_URL:http://localhost:18080}
  realm: ssb-realm
  client-id: ssb-backend
  client-secret: ${KEYCLOAK_CLIENT_SECRET}

server:
  port: 9000

fastapi:
  news:
    url: ${NEWS_SERVICE_URL:http://localhost:8000/news}
  analyse:
    url: ${ANALYSE_SERVICE_URL:http://localhost:8001/analyze/ppdt}
