spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SUPABASE_URL}/auth/v1
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/ppdtcore}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD}
  data:
    mongodb:
      uri: ${MONGO_URI}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  frontend-url: ${FRONTEND_URL:http://localhost:5173/}
  auth-url: ${SUPABASE_URL}

  config:
    activate:
      on-profile: dev
  
  # API Key for communicating with FastAPI
  api-key: ${SSB_API_KEY:ec9bvW4diGVw4iI2-lpDbdMe5a0cNhq1VoEIQm4T_Nc}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

deepgram:
  api-key: ${DEEPGRAM_API_KEY:}
  project-id: ${DEEPGRAM_PROJECT_ID:}



server:
  port: 9000

fastapi:
  srt: ${FASTAPI_SRT_URL:http://localhost:8000/srt/evaluate}
  wat: ${FASTAPI_WAT_URL:http://localhost:8000/wat/evaluate}
  tat: ${FASTAPI_TAT_URL:http://localhost:8000/tat/evaluate}
  news:
    url: ${NEWS_SERVICE_URL:http://localhost:8000/news}
  analyse:
    url: ${ANALYSE_SERVICE_URL:http://localhost:8000/evaluate}
ai:
  lecturette:
    url: ${AI_LECTURETTE_URL:http://localhost:8000/lecturette/evaluate}