spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/ppdtcore}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD}
  data:
    mongodb:
      uri: ${MONGO_URI}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  frontend-url: ${FRONTEND_URL:http://localhost:5173/}
  auth-url:

  config:
    activate:
      on-profile: dev

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}



server:
  port: 9000

fastapi:
  news:
    url: ${NEWS_SERVICE_URL:http://localhost:8001/news}
  analyse:
    url: ${ANALYSE_SERVICE_URL:http://localhost:8000/evaluate}
