spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:18080/realms/ssb-realm

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  data:
    mongodb:
      uri: mongodb://localhost:27017/testdb

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  h2:
    console:
      enabled: true

app:
  frontend-url: http://localhost:5173
  keycloak-url: http://localhost:18080

  config:
    activate:
      on-profile: test

server:
  port: 9000

keycloak:
  base-url: http://localhost:18080
  realm: ssb-realm
  client-id: ssb-backend
  client-secret: test-secret

fastapi:
  news:
    url: http://localhost:8000/news
  analyse:
    url: http://localhost:8001/analyze/ppdt
